### ISSUE TITLE
Lists within references are not aligned？

### ISSUE THREAD

**Issue by rXYZkit** [adrian-fuertes/typora-notion-theme#1]
![image](https://user-images.githubusercontent.com/45787079/154989714-d5e9ab5a-b745-4955-9c53-f5956ceacfec.png)

**Comment by adrian-fuertes** [comment]
Ohhh! Indentation wasn't properly implemented inside quotations. This has now been fixed in the [latest release](https://github.com/adrian-fuertes/typora-notion-theme/releases/tag/v1.0.1). Very nice catch, thanks a lot!
