### ISSUE TITLE
Cursor and text is invisible in 'inline-math' blocks

### ISSUE THREAD

**Issue by danielcs88** [adrian-fuertes/typora-notion-theme#11]
Similar to the previous issue, all text inside inline math blocks (e.g., $a^2$) are invisible.

![Notion Math Inline](https://user-images.githubusercontent.com/13838845/161408784-25d69353-cc23-45c1-b0bd-4257c8b4e5cc.gif)

I believe that this is probably because it is being inherited from a default from Codemirror. I don't know much CSS.

**Comment by NoneAndNever** [comment]
The same problem(black cursor) is also existed in the code block
