### ISSUE TITLE
Font color too bright

### ISSUE THREAD

**Issue by YH3Ai** [adrian-fuertes/typora-notion-theme#12]
Hi,
Thank you for this beautiful theme! Really enjoy it! The only problem I found while using is that the color for int, double, etc. in the code block seems too bright. (C++)
<img width="693" alt="Screen Shot" src="https://user-images.githubusercontent.com/30627535/173172554-ac6b83b2-69ff-44c6-aeca-364a31d3e48a.png">
I don't know how others feel about it but I think a color like #36ba6d may be a better substitution for the #48ff00 being used now for variable-3. 
Just some personal thoughts. Thanks again for creating this theme!

**Comment by adrian-fuertes** [comment]
Hey @Y1haoC! Thank you for the issue and the kind words. I will fix this issue in the upcoming release, the colors are due for an upgrade :)

**Comment by adrian-fuertes** [comment]
Hey @Y1haoC! This issues (and other code color problems) has been addressed on the latest [release](https://github.com/adrian-fuertes/typora-notion-theme/releases/tag/v1.2.0). Feel free to check it out and thank you for making a issue ❤️
