### ISSUE TITLE
How to change some colors inside code fence

### ISSUE THREAD

**Issue by vinamelody** [adrian-fuertes/typora-notion-theme#14]
Hi, I'm wondering how to change some of the font colors inside this code block because the `true` color is difficult to read.
Thanks a lot!

My original code is with `swift` language

```swift
let csvReadingOptions = CSVReadingOptions(
    hasHeaderRow: true,
    nilEncodings: ["", "nil", "na"],
    ignoresEmptyLines: true,
    delimiter: ","
)
```

<img width="678" alt="Screenshot 2022-08-17 at 10 42 09 PM" src="https://user-images.githubusercontent.com/990511/185168676-0ca2a746-fc84-4140-aa3b-bd7a365ac445.png">

**Comment by adrian-fuertes** [comment]
Hey @vinamelody! Thank you for leaving this issue. This is definitely a problem with the code color reproduction, I will fix it in the next release in a few weeks. If you want to tweak the colors yourself, you can edit the CodeFence properties in the theme files.

**Comment by vinamelody** [comment]
thanks @adrian-fuertes for the quick response and this theme!

**Comment by vinamelody** [comment]
Hi @adrian-fuertes ,so sorry, which cm class should I define for a boolean value?
