### ISSUE TITLE
Windows menu unreadable (Unibody interface)

### ISSUE THREAD

**Issue by enricodarodda** [adrian-fuertes/typora-notion-theme#3]
Hi,
this problem happens whenever you activate the "Unibody" interface on windows, and essentially, the colour of the text in the menù happens to be too light and it does not contrast enough to be readable as the following picture shows (left menu).
![image](https://user-images.githubusercontent.com/57716112/155717552-5d6a67d7-e75b-4565-863b-f2f6cfe8afda.png)
 and this happens both on the light and dark theme, but in the case of the dark theme, the unreadbale part is no more the menu but the right part, for example when you want to open a file etc... (as follows)
![image](https://user-images.githubusercontent.com/57716112/155717840-a4bb8e74-ebec-41bb-8fbd-1ac76092b58a.png)

**Comment by adrian-fuertes** [comment]
Thank you for the detailed issue, I will look into it and test it on Windows.

How do you exactly activate this view? I'm not familiar with it.

**Comment by enricodarodda** [comment]
no problem, you need to go to "File -> Settings -> (on the left side) appearance (i hope this is the english name typora uses, however it should be the second list item on the lft hand side of the settings) ->Window Style " and then you need it to set to Unibody.
In order for your changes to take effect you are required to restart the application.

**Comment by adrian-fuertes** [comment]
Hey! I just pushed a new release (v1.1.1) including a basic fix. I still want to work a little bit more on the colors/contrast to make it _beautiful_ but this should make the themes usable 😄

Thank you for reporting this issue and using the theme!

**Comment by enricodarodda** [comment]
thank you, i'll try it out!
