### ISSUE TITLE
Cursor colours in source mode are very hard to see

### ISSUE THREAD

**Issue by mutahiwachira** [adrian-fuertes/typora-notion-theme#4]
The cursor colour in the dark modes is almost invisible because it's black or dark grey. And in the light modes it's also very hard to see because it's white.

This is in source mode.

**Comment by adrian-fuertes** [comment]
Are you on Windows? For me the cursor looks fine (see the pictures)

<img width="147" alt="image" src="https://user-images.githubusercontent.com/62448367/155718723-1b41755c-145c-4593-b2ba-a58490bfa631.png">

<img width="180" alt="image" src="https://user-images.githubusercontent.com/62448367/155718741-a75aeaea-b40a-46ac-ba02-d517977acb33.png">

If that's the case I will look into it, I will be testing the theme on Windows soon. Thank you!

**Comment by mutahiwachira** [comment]
I am on Windows.

**Comment by adrian-fuertes** [comment]
Hey! I just pushed a new release (v1.1.1) including a fix for `source mode`. The cursor now follows the text color, so it's actually visible. There is still a problem within code blocks, I'm currently trying to fix that one, but `source mode` should work.

Thank you for reporting this issue and using the theme 😄!
